"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # NOTE: 今回は API サーバとして機能させるので、 staticfiles は不要です。
    # 'django.contrib.staticfiles',
    'app',
    'corsheaders',
]

ROOT_URLCONF = 'config.urls'

WSGI_APPLICATION = 'config.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# アプリケーションのための定数を定義します。
APP_HDF5_DRIVE_ID = os.environ['APP_HDF5_DRIVE_ID']
APP_HDF5_VERSION = os.environ['APP_HDF5_VERSION']
APP_HDF5_PATH_IN_APP = './app/hdf5.hdf5'
APP_PINCODE = os.environ['APP_PINCODE']
# Prediction に利用する定数です。
APP_INCEPTION_V3_TARGET_SIZE = (299, 299)
APP_CLASSES_FOR_N_FLOWERS = sorted([
    'Anthurium',
    'Bluebell',
    'Buttercup',
    'ColtsFoot',
    'Cowslip',
    'Crocus',
    'Daffodil',
    'Daisy',
    'Dandelion',
    'Fritillary',
    'Hydrangea',
    'Iris',
    'LilyValley',
    'Pansy',
    'Snowdrop',
    'Sunflower',
    'Tigerlily',
    'Tulip',
    'Windflower',
])
