name: CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  linting-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 . --count --max-complexity=10 --max-line-length=127 --show-source --statistics
      # NOTE: 今回はテストを作っていません。除きます。
      # - name: Test with pytest
      #   run: |
      #     pytest
